public/style.css, views/index.html
=> Updated HTML and CSS

.github/workflows/main.yml
This action automatically formats code with Prettier when a push is made to the main branch.
=> auto format code

backend/controllers/auth.controller.js, backend/middlewares/ValidatorErrorHandler.js, backend/routes/auth.route.js, backend/validators/AuthValidators.js
I Have fixed this issue and also removed unnecessary code from auth controller
=> resolve #15

backend/swagger.yml
Document Authentication API Endpoints with Swagger
=> ' resolve #23'

backend/controllers/url.controller.js
Blank excel file export when urls array is empty
=> blank export:  check if array has item

backend/models/UrlModel2.js
Worked on issue #64 
Changed Schema for better code readability and to know its purpose.
I have tested my code locally and it works as expected without any errors.
=> Changed UrlModel2 Schema

backend/controllers/url.controller.js, backend/routes/url.route.js, backend/validators/urlValidator.js
I have Resolved your issue number 16 by adding the url validations.
=> resolved #16

backend/controllers/authControllers/forgotPassword.controller.js, backend/controllers/authControllers/verifyEmail.controller.js, backend/routes/auth.route.js, backend/validators/AuthValidators.js
Fixed the issue number 19 of validation of forgot password and email verification
=> resolved #19

backend/models/UrlModel2.js, backend/routes/url.route.js
Close #52
Added customUrl field in Url Schema
=> Added customUrl field 

frontend/src/components/Signup.js
Added Cursor = pointer, so that the user can know it is clickable.
=> added cursor pointer to 'click here to login'

frontend/src/components/Navbar.js
@DhananjayThomble This PR fixes the contributor's nav items not showing for the non-logged-in users. Hope this meets your requirements. 
Fixes #100
=> Add contributors menu item for non logged in users

frontend/src/components/Home.js, frontend/src/components/LandingPage/form/LinkForm.js
I think the bug was initially from the the way the code was written. 
destructuring the response directly. actually, I'm not sure of the approach cuz I'm just seeing it. But I'm guessing the server doesn't send a res in that format (with the status code in it)
=> Shows aunauthenticated users alerts when shortening urls (401)

backend/controllers/category.controller.js, backend/models/UrlModel2.js, backend/models/urlModel.js, backend/routes/url.route.js, frontend/src/components/History.js, frontend/src/components/HistoryCard.js
@DhananjayThomble I have added few can you review and merge it (fixes #101 )
1. User Interface Design: added UI for managing URL categories. 
2. Backend Logic Implementation: Backend logic has been developed to associate URLs with categories. 
3. Filtering Options: I've integrated filtering options. 
I look forward to your feedback to ensure these features meet our project's goals.
=> URL Categories Feature

frontend/src/components/History.js, frontend/src/components/HistoryCard.js, frontend/src/components/pagination.js
@DhananjayThomble Redesign the URL History page and add pagination support with 3 cards in one page. (fixes #33)
=> add pagination and redesign URLs history page.

backend/models/UserModel.js, backend/models/linkInBioPageModel.js
**In this pull request i have added the linkInBio schema, model**
* that will fix the issue #92
=> added linkInBio schema, model

backend/swagger.yml
This pull request updates the Swagger API documentation to include the Category Filter functionality for the URL API. It enhances the existing API documentation to provide more clarity and detail on how to filter URLs by category and update their categories.
- Added a new API endpoint for filtering URLs by category.
- Provided detailed descriptions, request parameters, and response structures for both endpoints.
The Category Filter functionality is a valuable feature for our URL API, and we want to ensure that developers have clear and comprehensive documentation to use this feature effectively. This update aligns with our goal to provide a better developer experience and helps users understand and leverage the category filtering capabilities of our API.
@DhananjayThomble you can test the …
=> api documentation updated

frontend/src/App.js, frontend/src/components/Linkinbio.js, frontend/src/components/Navbar.js, frontend/src/components/ProfileForm.js, frontend/src/components/ProfilePage.js, frontend/src/components/linkinbio.css
Designed Link-in-bio page and features such as QR Code, Delete, Copy to clipboard.
Users can also view their link-in-bio page and share it with others.
=> Issue fixed: Frontend Development for "Link-in-Bio" Page #90

backend/controllers/CurrentUserController/changeEmail.controller.js, backend/controllers/CurrentUserController/changeName.controller.js, backend/controllers/CurrentUserController/getCurrentUser.controller.js, backend/controllers/authControllers/login.controller.js, backend/package.json, backend/routes/auth.route.js
1- Added a endpoint to see current user data
2- Added a endpoint to change email
3- Added a endpoint to change the name
=> #112 Added Endpoint to retrieve user data and updating user data

backend/controllers/CurrentUserController/changeEmail.controller.js, backend/controllers/CurrentUserController/changeName.controller.js, backend/routes/auth.route.js, backend/utils/helperfunc.js, backend/validators/AuthValidators.js
added email validation function and validations for name and email
fixed : #112
=> improvement: added validations for userinfo updation and function to validate email

backend/controllers/adminControllers/adminSignup.js, backend/controllers/authControllers/signup.js, backend/controllers/authControllers/verifyEmail.js, backend/routes/userAuth.route.js, backend/utils/mailSend.js, backend/validators/authValidators.js, backend/views/welcome_email_template.ejs
update the welcome email template and refactored the signup controller
=> update welcome email template, refactor signup controller

README.md, backend/controllers/authControllers/forgotPassword.js, backend/utils/mailSend.js, backend/views/reset_password_email_template.ejs, frontend/src/components/ForgotPassword.jsx, frontend/src/components/ResetPassword.jsx
update password reset functionality &
add password reset email template
- Are there environment variables that should be set?
Yes, Add `FRONTEND_URL=<your-frontend-url>` to /backend's .env file
=> update password reset functionality,

package.json
=> package.json and scripts for root dir

frontend/package.json
=> removing react-scripts library

README.md
=> Enhancing project setup docs

backend/models/Feedback.js, backend/swagger.yml, frontend/src/components/FeedbackForm.jsx
This commit / PR will complete the pending logic of handling feedback form
submission in FeedbackForm.jsx component.
- Add logic to submit feedback data to the backend route /auth/fedback.
- Move logic of resetting state to separate method.
- Properly handle errors & tell user if the operation was success.
References PR https://github.com/DhananjayThomble/URL-Shortener-App/pull/180.
(This is a hacktoberfest submission 🎃)
This change requires no documentation changes / updates.
- Are there environment variables that should be set?
> No
- What are the minimal test data to have?
> None required
- Any other important info that could help to test that PR
> No
- I have read the [contributing guide](https://github.com/DhananjayThomble/URL-Shortener-App/blob/main/CONTRIBUTING.md)
- My code …
=> Feat: Integrate feedback form with backend API
